version: 2
updates:
  - package-ecosystem: pip
    directory: /feedseek
    schedule: { interval: weekly }
  - package-ecosystem: gradle
    directory: /kanarek
    schedule: { interval: weekly }
    groups:
      androidx:
        patterns: ["androidx*"]
      kotlin:
        patterns: ["org.jetbrains.kotlin*"]
  - package-ecosystem: npm
    directory: /kanarek/worker
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /feeds-proxy
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
