---
name: Lint

on:  # yamllint disable-line rule:truthy
  push:
    paths-ignore:
      - 'feedseek/feeds/**'
      - 'feedseek/cache/**'
  pull_request: null

permissions: {}
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@v8.7.0  # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_YAML: true
          #VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON: true

  test:
    name: Trufflehog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
